import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

import Navbar from "@/lib/ui/navbar";
import "./globals.css";

const inter = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Simple Pokedex v3',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className='bg-white rounded'>
          {children}
        </main>
      </body>
    </html>
    
  )
}
