import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Navbar from "@/ui/navbar";
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Simple Pokedex v3',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className='h-screen mx-[auto]'>
          {children}
        </main>
      </body>
    </html>
  )
}
