import type { Metadata } from "next";
import { MenuIcon } from "lucide-react";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <nav className='relative flex justify-end items-center w-full h-12 px-2 bg-pokeballred text-white'>
          <p className='absolute left-2  font-bold'>Simple Pokedex v3</p>
          <MenuIcon className='p-1 w-8 h-8 rounded-sm' />
        </nav>
        {children}
      </body>
    </html>
  );
}
